French translation refinements
Ardour/ardour pull request #572
Opened 2020-10-14 21:46 UTC by trebmuh

2020-10-15 00:14 UTC, keryell requested changes
Bien !
Juste quelques problèmes de minuscules/majuscules...

2020-10-15 00:14 UTC, keryell commented on gtk2_ardour/po/fr.po
> +"Vous pouvez inclure \"tiret du 6\" \"tiret du 8\" et \":\" dans une Étiquette."
```suggestion
"Vous pouvez inclure \"tiret du 6\" \"tiret du 8\" et \":\" dans une étiquette."
```

2020-10-15 00:14 UTC, keryell commented on gtk2_ardour/po/fr.po
> +msgstr "Ex: \"dynamique de-esser vocal\" représente 3 Étiquettes."
```suggestion
msgstr "Ex: \"dynamique de-esser vocal\" représente 3 étiquettes."
```

2020-11-09 00:12 UTC, trebmuh commented
closing in favor of #580

2020-11-09 00:12 UTC, closed without merging